name: Frequent Auto Commit (every 5 min)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "Glober-Developer"
          git config --global user.email "coder.person01@gmail.com"

      - name: Make a frequent commit
        run: |
          echo "Committed at $(date)" >> daily.txt
          git add daily.txt
          git commit -m "Auto commit: $(date)" || echo "No changes to commit"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git push
