name: Frequent Auto Commit (every 5 min)

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"

      - name: Make a frequent commit
        run: |
          echo "Committed at $(date)" >> daily.txt
          git add daily.txt
          git commit -m "Auto commit: $(date)"
          git push
